from . import shopify_sync_log
from . import shopify_sync_mixin
from . import res_company
from . import account_journal
from . import account_tax
from . import account_move
from . import product_template
from . import product_product
from . import res_partner
from . import sale_order
from . import stock_warehouse
